---
- name: Ensure search service is running
  win_service: 
   name: WSearch
   state: started

- name: Create temp directory
  win_file: 
    path: C:\Temp
    state: directory

- name: Install IIS Web-Server with sub features and management tools
  win_feature:
    name: Web-Server
    state: present
    restart: False
    include_sub_features: True
    include_management_tools: True

- name: Install .NET 3.5
  win_feature:
    name: Web-Asp-Net
    state: present

- name: Install .NET 4.5
  win_feature:
    name: Web-Asp-Net45
    state: present

- name: Install SNMP
  win_feature:
    name: SNMP-Service
    state: present
    include_sub_features: True
    include_management_tools: True

- name: Install WIF 3.5
  win_feature:
    name: Windows-Identity-Foundation
    state: present
