---
- name: Install IIS Web-Server with sub features and management tools
  win_feature:
    name: Web-Server
    state: present
    restart: False
    include_sub_features: True
    include_management_tools: True

- name: open regedit
  win_psexec: 
    command: regedit.exe
    interactive: yes
    system: yes